apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: queue-proxy
  description: Queue Proxy
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: kubecon-squad
  system: podcast
