apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: queue-proxy
  description: Queue Proxy
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/external-spotify-portal-demo/example-org/tree/main/components/tech-docs/queue-proxy-docs
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: team-b
  system: podcast
