apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: "Our Internal LLM"
  name: searcher
  description: Searcher
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: user:guest
